service:
  name: leve-menina-sls

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: sa-east-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/sendMailIAM.yml):sendMailIAM}
    - ${file(iam/mailQueueIAM.yml):MailQueueIAM}

resources:
  Resources:
    MailQueue: ${file(resources/mailQueue.yml):MailQueue}

functions:
  sendMailQueue:
    handler: src/handlers/sendMailQueue.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1

  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - http:
          method: POST
          path: /send
          cors: true

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
  bundle:
    linting: false #é desaconselhável usar esse parâmetro como false
